name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: "24.0"
      - name: Run Lint
        run: rebar3 fmt --check
      - name: Run Tests
        run: rebar3 eunit
